Feature/4 rows
MirkoZorich/flutter_app pull request #1
Opened 2021-11-22 19:12 UTC by MirkoZorich

2021-11-23 12:08 UTC, artem-zaitsev requested changes

2021-11-23 12:08 UTC, artem-zaitsev commented on lib/main.dart
> +                IconData(57504, fontFamily: 'MaterialIcons'),
Есть класс Icons - там много статичных констант с иконками. И back там тоже есть
Icons.arrow_back

2021-11-23 12:08 UTC, artem-zaitsev commented on lib/main.dart
> +              onPressed: null,
почему кнопка некативна для нажатия?

2021-11-23 16:33 UTC, MirkoZorich commented
Класс иконки заменил, добавил навигацию

2021-11-24 06:52 UTC, artem-zaitsev approved these changes

2021-11-24 06:52 UTC, merged